### PR TITLE
use constructor

### PR DESCRIPTION
**Pull request by benjyz**

### CODE REVIEW

**Comment by thanhson1085** [comment]
Nice to have. Will merge later. Now `constructor` still have problem with `abigen` in tomochain codebased.

**Comment by benjyz** [comment]
right, I was wondering about how the code will be shared between node and the dapp. would it make sense to add test for solidity validator code only?

**Comment by thanhson1085** [comment]
yep, need some pull request for tests for solidity codes.

Dapp read/write data to smart contract via EVM in node. Consensus will be read Smart Contract to know who is masternode. The first one is done, but the second one is developing, will done soon.

**Comment by thanhson1085** [comment]
It fixed in #86

**Pull request closed without merging**
